### PR TITLE
Add fastero to gallery

### PR DESCRIPTION
**Pull request by wasi-master**
The profiling category is only there because I can't think of any others. Suggestions appreciated

### CODE REVIEW

**Comment by willmcgugan** [comment]
Thanks @wasi-master !

The image is a little too large. The max size is 800x600

**Comment by wasi-master** [comment]
@willmcgugan is that a necessity? Because now I would need to further lower the resolution or crop the image. 

The image size is pretty low already though

**Comment by willmcgugan** [comment]
Afraid so. Think of it as a thumbnail. You can put a full-res version on the repo...

**Comment by wasi-master** [comment]
@willmcgugan Done

**Pull request merged**
